name: EIDL-Lumapi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - autograd
  - gdspy
  - h5py
  - matplotlib
  - mpi4py
  - numpy
  - pip
  - psutil
  - scipy
  - tqdm
  - pip:
      - -e ..
